name: Lint
on:
  pull_request:
    branches: [ dev, main ]
  push:
    branches: [ dev ]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.24.x' }
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.2
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=3m
